/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/create_user_profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create or update user profile
         * @description Stores tax-related profile information for the authenticated user in Firestore.
         */
        post: operations["createUserProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/get_tax_documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tax documents
         * @description Returns all tax documents belonging to the authenticated user.
         */
        get: operations["getTaxDocuments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/get_tax_summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get tax summary
         * @description Returns an aggregated summary of the user's tax situation including
         *     document counts by type and processing status. Response is cached for 5 minutes.
         */
        get: operations["getTaxSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/process_document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Manually trigger document processing
         * @description Re-processes a specific tax document. Useful when automatic processing
         *     failed or needs to be retried. Only the document owner can trigger this.
         */
        post: operations["processDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/get_document_status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get document processing status
         * @description Returns the current status and extracted metadata for a document.
         *     Response is cached for 1 minute.
         */
        get: operations["getDocumentStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service info
         * @description Returns service status and available routes. No authentication required.
         */
        get: operations["getServiceInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns service health including Firebase and OpenAI connectivity. No authentication required.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/firebase-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Firebase connectivity check
         * @description Verifies Firestore is reachable and lists top-level collections.
         */
        get: operations["getFirebaseStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/debug/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List sample user IDs (dev only)
         * @description Lists up to 10 unique user IDs from the taxDocuments collection. For development debugging only.
         */
        get: operations["debugListUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sample/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve sample file (dev only)
         * @description Returns a static sample file from the backend/sample directory.
         */
        get: operations["getSampleFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/auditor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run AuditorAgent
         * @description Runs the AuditorAgent against a user's tax documents.
         *     The agent checks for:
         *     - Data quality issues (missing fields, OCR errors)
         *     - IRS audit triggers (high deduction ratios, round numbers)
         *     - Income cross-references across documents
         *     - Produces a structured risk report (LOW / MODERATE / ELEVATED / HIGH)
         */
        post: operations["runAuditorAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/accountant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run AccountantAgent
         * @description Runs the AccountantAgent against a user's tax documents.
         *     The agent:
         *     - Estimates federal tax liability from income data
         *     - Identifies applicable deductions and credits
         *     - Compares filing scenarios (MFJ vs MFS, itemize vs standard)
         *     - Generates a tax preparation summary
         *
         *     Run the AuditorAgent first to validate data quality before the AccountantAgent.
         */
        post: operations["runAccountantAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserProfile: {
            /**
             * @description User's full name
             * @example Jane Doe
             */
            name: string;
            /**
             * @description Tax identification number (SSN or EIN)
             * @example 123-45-6789
             */
            taxId: string;
            /**
             * @description Type of business entity
             * @example sole_proprietor
             */
            businessType: string;
            /** Format: date-time */
            readonly updatedAt?: string;
        };
        DocumentMetadata: {
            name?: string;
            tax_id?: string;
            /** Format: float */
            income?: number;
            /** Format: float */
            tax_due?: number;
            /** @example 2024 */
            tax_year?: string;
            /** @example single */
            filing_status?: string;
            confidence_scores?: {
                [key: string]: number;
            };
            parser_version?: string;
            /** Format: date-time */
            processing_timestamp?: string;
            extraction_success?: boolean;
        };
        TaxDocument: {
            /** @description Firestore document ID */
            id: string;
            /** @description File name */
            name: string;
            /** @description Original uploaded file name */
            originalName?: string;
            /**
             * @description MIME type
             * @example application/pdf
             */
            type: string;
            /** @description File size in bytes */
            size: number;
            /** Format: date-time */
            uploadDate: string;
            /**
             * Format: uri
             * @description Cloud Storage download URL
             */
            url: string;
            /** @description Cloud Storage path */
            path: string;
            /** @enum {string} */
            status: "pending" | "processed" | "error";
            metadata?: components["schemas"]["DocumentMetadata"];
            /** @description Error message if status is error */
            error?: string;
        };
        TaxSummary: {
            totalDocuments: number;
            /** Format: date-time */
            lastUpdated?: string | null;
            /** @description Count of documents per MIME type */
            documentTypes: {
                [key: string]: number;
            };
            processingStatus: {
                processed: number;
                pending: number;
                error: number;
            };
            recentDocuments: components["schemas"]["TaxDocument"][];
        };
        ProcessingResult: {
            success: boolean;
            documentId: string;
            error?: string;
            metadata?: components["schemas"]["DocumentMetadata"];
        };
        DocumentStatusResponse: {
            /** @enum {string} */
            status: "pending" | "processed" | "error";
            metadata?: components["schemas"]["DocumentMetadata"];
            error?: string;
        };
        AgentRequest: {
            /** @description Firebase user ID */
            user_id: string;
            /** @description Custom instruction for the agent (optional — defaults to a full analysis) */
            task?: string;
        };
        AccountantAgentRequest: components["schemas"]["AgentRequest"] & {
            /**
             * @default single
             * @enum {string}
             */
            filing_status: "single" | "married_filing_jointly" | "married_filing_separately" | "head_of_household";
        };
        AgentResponse: {
            /** @example ok */
            status: string;
            user_id: string;
            /** @description Agent's analysis output (Markdown text) */
            output: string;
        };
        HealthResponse: {
            /** @example ok */
            status: string;
            firebase: boolean;
            openai: boolean;
        };
        ErrorResponse: {
            error: string;
        };
    };
    responses: {
        /** @description Missing or invalid Firebase ID token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Document does not belong to the authenticated user */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Invalid request body or missing required fields */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Unexpected server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfile"];
            };
        };
        responses: {
            /** @description Profile saved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getTaxDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of documents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        documents: components["schemas"]["TaxDocument"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getTaxSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tax summary */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxSummary"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    processDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Firestore document ID */
                    documentId: string;
                };
            };
        };
        responses: {
            /** @description Processing result (success or failure) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getDocumentStatus: {
        parameters: {
            query: {
                /** @description Firestore document ID */
                documentId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document status */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentStatusResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getServiceInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                        service?: string;
                        firebase?: string;
                        routes?: string[];
                    };
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getFirebaseStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Firebase is connected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                        collections?: string[];
                    };
                };
            };
            /** @description Firebase not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    debugListUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sample users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        users?: {
                            user_id?: string;
                            sample_doc_type?: string;
                            status?: string;
                        }[];
                    };
                };
            };
            /** @description Firebase not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSampleFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File contents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description File not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    runAuditorAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentRequest"];
            };
        };
        responses: {
            /** @description Audit risk report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
            /** @description Firebase not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    runAccountantAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountantAgentRequest"];
            };
        };
        responses: {
            /** @description Tax preparation summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
            /** @description Firebase not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
